//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarteraGeneral {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MisConsultas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MisConsultas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarteraGeneral.MisConsultas", typeof(MisConsultas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT a.IdAdjudicacion AS IdAdjudicacion,t.NombreCompleto AS Titular1,c.NombreCompleto AS Titular2,a.IdTercero1 AS idTercero1,a.IdTercero2 AS idTercero2,a.IdProyecto AS IdProyecto,a.IdInmueble AS IdInmueble
        ///FROM ((hotelalttum.adjudicacion a
        ///LEFT JOIN Contabilidad_alttum.terceros t ON((t.IdTercero = (a.IdTercero1))))
        ///LEFT JOIN Contabilidad_alttum.terceros c ON((c.IdTercero = (a.IdTercero2))))
        ///where TipoOperacion=&apos;Normal&apos; And Estado=&apos;Aprobado&apos;.
        /// </summary>
        internal static string CnsAdjudica003 {
            get {
                return ResourceManager.GetString("CnsAdjudica003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///c.IdTercero,
        ///t.NombreCompleto,
        ///c.IdCargo,
        ///s.NombreCargo,
        ///c.Comision1
        ///FROM comision c
        ///JOIN Contabilidad_alttum.terceros t ON t.idtercero=c.idtercero
        ///JOIN tablacomision s ON c.idcargo=s.idCargo
        ///WHERE IdAdjudicacion=@Parametro1
        ///ORDER BY c.IdCargo.
        /// </summary>
        internal static string CnsDatosComisionxAdj {
            get {
                return ResourceManager.GetString("CnsDatosComisionxAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select 
        ///m.IdLote,
        ///m.Fecha,
        ///m.IdAdjudicacion,
        ///d.nombrecompleto as Cliente,
        ///m.Contrato,
        ///m.ValorContrato,
        ///m.Estado,
        ///c.TipoOperacion,
        ///m.ReferenciaMonterey
        ///From enviosmonterey m
        ///join adjudicacion c on c.IdAdjudicacion=m.IdAdjudicacion
        ///join Contabilidad_alttum.terceros d on d.idtercero=c.IdTercero1
        ///Where c.TipoOperacion=&apos;AlttumMonterey&apos;.
        /// </summary>
        internal static string CnsEnviosAltumMonterey {
            get {
                return ResourceManager.GetString("CnsEnviosAltumMonterey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select 
        ///m.IdLote,
        ///m.Fecha,
        ///m.IdAdjudicacion,
        ///d.nombrecompleto as Cliente,
        ///m.Contrato,
        ///m.ValorContrato,
        ///c.FinanciacionMfs,
        ///c.CuotaMfs,
        ///m.Estado,
        ///c.TipoOperacion,
        ///m.ReferenciaMonterey,
        ///m.Clasificacion
        ///From enviosmonterey m
        ///join adjudicacion c on c.IdAdjudicacion=m.IdAdjudicacion
        ///join Contabilidad_alttum.terceros d on d.idtercero=c.IdTercero1
        ///Where c.TipoOperacion=&apos;Monterey&apos;.
        /// </summary>
        internal static string CnsEnviosMonterey {
            get {
                return ResourceManager.GetString("CnsEnviosMonterey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///a.IdAdjudicacion ,
        ///a.FechaContrato,
        ///a.Contrato,
        ///a.Trm,
        ///a.Valor,
        ///convert(ROUND((a.Valor*a.trm),2),decimal (18,2)) as ValorMonedaLocal,
        ///a.FinanciacionMfs,
        ///a.CuotaMfs,
        ///a.IdTercero1,
        ///t.nombrecompleto as Cliente
        ///from adjudicacion a 
        ///LEFT JOIN Contabilidad_alttum.terceros t on a.IdTercero1=t.IdTercero
        ///where IdAdjudicacion in(Select IdAdjudicacion From enviosmonterey Where IdLote=@Parametro1).
        /// </summary>
        internal static string CnsEnviosxIdLote {
            get {
                return ResourceManager.GetString("CnsEnviosxIdLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///a.IdAdjudicacion,
        ///a.FechaContrato,
        ///a.Contrato,
        ///a.Trm,
        ///a.Valor,
        ///convert(ROUND((a.Valor*a.trm),2),decimal (18,2)) as ValorMonedaLocal,
        ///a.FinanciacionMfs,
        ///a.CuotaMfs,
        ///a.IdTercero1,
        ///t.nombrecompleto as Cliente
        ///from adjudicacion a 
        ///LEFT JOIN Contabilidad_alttum.terceros t on a.IdTercero1=t.IdTercero
        ///where a.tipooperacion=&apos;Monterey&apos;
        ///and a.negociacion=&apos;Pendiente&apos;
        ///or IdAdjudicacion in (Select IdAdjudicacion From enviosmonterey where IdLote=@Parametro1).
        /// </summary>
        internal static string CnsModNegocionsNoEnviadoMonterey {
            get {
                return ResourceManager.GetString("CnsModNegocionsNoEnviadoMonterey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        ///f.Fecha,
        ///f.IdGestor,
        ///t.NombreCompleto,
        ///f.IdAdjudicacion,
        ///c.Identificacion as Cliente,
        ///c.Contrato,
        ///f.Valor
        ///FROM fondosmonterrey f
        ///JOIN Contabilidad_alttum.terceros t
        ///ON f.IdGestor=t.IdTercero
        ///JOIN 004cnsadjudica c 
        ///on f.IdAdjudicacion=c.IdAdjudicacion
        ///where f.IdGestor=@Parametro1.
        /// </summary>
        internal static string CnsMovimientoFondosxIdGestor {
            get {
                return ResourceManager.GetString("CnsMovimientoFondosxIdGestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  SELECT DISTINCT(Rsm.IdAdjudicacion)IdAdjudicacion,Cliente,convert((sum(PagoNeto)),DEC (18,2)) TotalComision
        ///FROM
        ///(
        ///SELECT a7.* 
        ///,
        /// (A7.TotalComision-A7.Retencion-A7.Anticipo-A7.DctoFondo)As PagoNeto
        ///FROM
        ///(SELECT A6.*,if(PdteFondo &gt; ReteFondo,ReteFondo,PdteFondo)As DctoFondo
        ///FROM
        ///(
        ///Select IdAdjudicacion,Cliente,Nombres as Gestor,NombreCargo as Cargo,Comision1,Comision2,Comision3,Lqd1,Lqd2,Lqd3,PagoComision,TotalComision,Retencion,ReteFondo,SaldoAnticipo Anticipo,
        ///Saldofondo,TopeFondo,(TopeFondo-S [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ComisionesMontererTiempoRsm {
            get {
                return ResourceManager.GetString("ComisionesMontererTiempoRsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT a7.* 
        ///,
        /// (A7.TotalComision-A7.Retencion-A7.Anticipo-A7.DctoFondo)As PagoNeto
        ///FROM
        ///(SELECT A6.*,if(PdteFondo &gt; ReteFondo,ReteFondo,PdteFondo)As DctoFondo
        ///FROM
        ///(
        ///Select IdAdjudicacion,Cliente,Nombres as Gestor,NombreCargo as Cargo,Comision1,Comision2,Comision3,Lqd1,Lqd2,Lqd3,PagoComision,TotalComision,Retencion,ReteFondo,SaldoAnticipo Anticipo,
        ///Saldofondo,TopeFondo,(TopeFondo-SaldoFondo)PdteFondo
        ///
        ///From
        ///(
        ///SELECT A4.*
        ///FROM
        ///(
        ///select A3.*,convert( (A3.TotalComision*A3.TasaRetencion/100),dec  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ComisionesMonterey {
            get {
                return ResourceManager.GetString("ComisionesMonterey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 
        /// SELECT a7.* 
        ///,
        /// (A7.TotalComision-A7.Retencion-A7.Anticipo-A7.DctoFondo)As PagoNeto
        ///FROM
        ///(SELECT A6.*,if(PdteFondo &gt; ReteFondo,ReteFondo,PdteFondo)As DctoFondo
        ///FROM
        ///(
        ///Select
        ///CAST(concat(IdCargo,&apos;ADJ&apos;,IdAdjudicacion)as char) IdFinanciacion,IdGestor,
        /// IdAdjudicacion,Cliente,Nombres as Gestor,IdCargo, NombreCargo as Cargo,Comision1,Comision2,Comision3,Lqd1,Lqd2,Lqd3,PagoComision,TotalComision,Retencion,ReteFondo,SaldoAnticipo Anticipo,
        ///Saldofondo,TopeFondo,(TopeFondo-SaldoFondo)PdteFondo,Dias,Fech [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ComisionesMontereyTimpoAdj {
            get {
                return ResourceManager.GetString("ComisionesMontereyTimpoAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT a7.* 
        ///,
        /// (A7.TotalComision-A7.Retencion-A7.Anticipo-A7.DctoFondo)As PagoNeto
        ///FROM
        ///(SELECT A6.*,if(PdteFondo &gt; ReteFondo,ReteFondo,PdteFondo)As DctoFondo
        ///FROM
        ///(
        ///Select
        ///CAST(concat(IdCargo,&apos;ADJ&apos;,IdAdjudicacion)as char) IdFinanciacion,IdGestor,
        /// IdAdjudicacion,Cliente,Nombres as Gestor,IdCargo,NombreCargo as Cargo,Comision1,Comision2,Comision3,Lqd1,Lqd2,Lqd3,PagoComision,TotalComision,Retencion,ReteFondo,SaldoAnticipo Anticipo,
        ///Saldofondo,TopeFondo,(TopeFondo-SaldoFondo)PdteFondo,Cuenta
        ///
        ///Fro [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ComisionesMontereyxAdj {
            get {
                return ResourceManager.GetString("ComisionesMontereyxAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  
        /// 
        ///
        ///SELECT a7.* 
        ///,
        /// (A7.TotalComision-A7.Retencion-A7.Anticipo-A7.DctoFondo)As PagoNeto
        ///FROM
        ///(SELECT A6.*,if(PdteFondo &gt; ReteFondo,ReteFondo,PdteFondo)As DctoFondo
        ///FROM
        ///(
        ///Select
        ///CAST(concat(IdCargo,&apos;ADJ&apos;,IdAdjudicacion)as char) IdFinanciacion,
        /// IdAdjudicacion,Cliente,Nombres as Gestor,IdCargo,NombreCargo as Cargo,Comision1,Comision2,Comision3,Lqd1,Lqd2,Lqd3,PagoComision,TotalComision,Retencion,ReteFondo,SaldoAnticipo Anticipo,
        ///Saldofondo,TopeFondo,(TopeFondo-SaldoFondo)PdteFondo,Dias,FechaCont [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ComisionesMonterreyTiempo {
            get {
                return ResourceManager.GetString("ComisionesMonterreyTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select * From
        ///From
        ///(
        ///SELECT A4.*, (A4.TotalComision-A4.Retencion-A4.SaldoAnticipo)As PagoNeto
        ///FROM
        ///(
        ///select A3.*,convert( (A3.TotalComision*A3.TasaRetencion/100),dec (18,2))Retencion
        ///
        ///FROM
        ///(select A2.* ,(A2.Lqd1+A2.Lqd2+A2.Lqd3-A2.pagocomision)TotalComision,g.Cuenta,if( g.retencion is null,0,g.retencion)TasaRetencion
        ///from 
        ///(
        ///Select A1.*,
        ///convert( IF(A1.Recaudo&gt;=(A1.BaseRecaudo*1),A1.BaseComision*A1.Comision1/A1.Veces/100,0),dec(18,2)) Lqd1,
        ///convert( IF(A1.Recaudo&gt;=(A1.BaseRecaudo*2),A1.BaseCom [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ComisionesPorPagarGral {
            get {
                return ResourceManager.GetString("ComisionesPorPagarGral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 
        ///Select IdAdjudicacion,Cliente,Nombres as Gestor,NombreCargo as Cargo,Comision1,Comision2,Comision3,Lqd1,Lqd2,Lqd3,PagoComision,TotalComision,Retencion,SaldoAnticipo Anticipo,PagoNeto
        ///
        ///From
        ///(
        ///SELECT A4.*, (A4.TotalComision-A4.Retencion-A4.SaldoAnticipo)As PagoNeto
        ///FROM
        ///(
        ///select A3.*,convert( (A3.TotalComision*A3.TasaRetencion/100),dec (18,2))Retencion
        ///
        ///FROM
        ///(select A2.* ,(A2.Lqd1+A2.Lqd2+A2.Lqd3-A2.pagocomision)TotalComision,g.Cuenta,if( g.retencion is null,0,g.retencion)TasaRetencion
        ///from 
        ///(
        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ComisionesPorPagarNetas {
            get {
                return ResourceManager.GetString("ComisionesPorPagarNetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select * From
        ///(
        ///SELECT A4.*, (A4.TotalComision-A4.Retencion-A4.SaldoAnticipo)As PagoNeto
        ///FROM
        ///(
        ///select A3.*,convert( (A3.TotalComision*A3.TasaRetencion/100),dec (18,2))Retencion
        ///
        ///FROM
        ///(select A2.* ,(A2.Lqd1+A2.Lqd2+A2.Lqd3-A2.pagocomision)TotalComision,g.Cuenta,if( g.retencion is null,0,g.retencion)TasaRetencion
        ///from 
        ///(
        ///Select A1.*,
        ///convert( IF(A1.Recaudo&gt;=(A1.BaseRecaudo*1),A1.BaseComision*A1.Comision1/A1.Veces/100,0),dec(18,2)) Lqd1,
        ///convert( IF(A1.Recaudo&gt;=(A1.BaseRecaudo*2),A1.BaseComision* [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ComisionesPorPagarPorAdj {
            get {
                return ResourceManager.GetString("ComisionesPorPagarPorAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT DISTINCT(Rsm.IdAdjudicacion)IdAdjudicacion,Cliente,convert((sum(PagoNeto)),DEC (18,2)) TotalComision
        ///FROM
        ///(
        ///SELECT a7.* 
        ///,
        /// (A7.TotalComision-A7.Retencion-A7.Anticipo-A7.DctoFondo)As PagoNeto
        ///FROM
        ///(SELECT A6.*,if(PdteFondo &gt; ReteFondo,ReteFondo,PdteFondo)As DctoFondo
        ///FROM
        ///(
        ///Select IdAdjudicacion,Cliente,Nombres as Gestor,NombreCargo as Cargo,Comision1,Comision2,Comision3,Lqd1,Lqd2,Lqd3,PagoComision,TotalComision,Retencion,ReteFondo,SaldoAnticipo Anticipo,
        ///Saldofondo,TopeFondo,(TopeFondo-Sa [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ComsionesMontereyRsm {
            get {
                return ResourceManager.GetString("ComsionesMontereyRsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select if(max(id) is null,1,max(id)+1)Cosecutivo from lotesenvio.
        /// </summary>
        internal static string ConsecutivoLotesEnvio {
            get {
                return ResourceManager.GetString("ConsecutivoLotesEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select IdComision,idGestor,Nombres as Asesor,IdCargo,NombreCargo,Cuenta,Comision1,comision2,Comision3,lqd1,lqd2,lqd3,PagoComision,
        ///totalcomision,Retencion,SaldoAnticipo,PagoNeto From 
        ///
        ///(
        ///SELECT A4.*, (A4.TotalComision-A4.Retencion-A4.SaldoAnticipo)As PagoNeto
        ///FROM
        ///(
        ///select A3.*,convert( (A3.TotalComision*A3.TasaRetencion/100),dec (18,2))Retencion
        ///
        ///FROM
        ///(select A2.* ,(A2.Lqd1+A2.Lqd2+A2.Lqd3-A2.pagocomision)TotalComision,g.Cuenta,if( g.retencion is null,0,g.retencion)TasaRetencion
        ///from 
        ///(
        ///Select [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ConsultaPagoComisionPorAdj {
            get {
                return ResourceManager.GetString("ConsultaPagoComisionPorAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select DISTINCTROW IdAdjudicacion From  
        ///
        ///(
        ///SELECT A4.*, (A4.TotalComision-A4.Retencion-A4.SaldoAnticipo)As PagoNeto
        ///FROM
        ///(
        ///select A3.*,convert( (A3.TotalComision*A3.TasaRetencion/100),dec (18,2))Retencion
        ///
        ///FROM
        ///(select A2.* ,(A2.Lqd1+A2.Lqd2+A2.Lqd3-A2.pagocomision)TotalComision,g.Cuenta,if( g.retencion is null,0,g.retencion)TasaRetencion
        ///from 
        ///(
        ///Select A1.*,
        ///convert( IF(A1.Recaudo&gt;=(A1.BaseRecaudo*1),A1.BaseComision*A1.Comision1/A1.Veces/100,0),dec(18,2)) Lqd1,
        ///convert( IF(A1.Recaudo&gt;=(A1.Ba [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ListaComisionesPorPagarNetas {
            get {
                return ResourceManager.GetString("ListaComisionesPorPagarNetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///a.IdAdjudicacion,
        ///a.FechaContrato,
        ///a.Contrato,
        ///a.Trm,
        ///a.Valor,
        ///convert(ROUND((a.Valor*a.trm),2),decimal (18,2)) as ValorMonedaLocal,
        ///a.IdTercero1,
        ///t.nombrecompleto as Cliente
        ///from adjudicacion a 
        ///LEFT JOIN Contabilidad_alttum.terceros t on a.IdTercero1=t.IdTercero
        ///where a.tipooperacion=&apos;AltumMonterey&apos; and a.Estado=&apos;Normal&apos;
        ///and a.negociacion=&apos;Pendiente&apos;
        ///or IdAdjudicacion in (Select IdAdjudicacion From enviosmonterey where IdLote=@Parametro1).
        /// </summary>
        internal static string ModNegociosAltumMonterey {
            get {
                return ResourceManager.GetString("ModNegociosAltumMonterey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///a.IdAdjudicacion,
        ///a.FechaContrato,
        ///a.Contrato,
        ///a.Trm,
        ///a.Valor,
        ///convert(ROUND((a.Valor*a.trm),2),decimal (18,2)) as ValorMonedaLocal,
        ///a.IdTercero1,
        ///t.nombrecompleto as Cliente
        ///from adjudicacion a 
        ///LEFT JOIN Contabilidad_alttum.terceros t on a.IdTercero1=t.IdTercero
        ///where a.tipooperacion=&apos;Normal&apos; and a.Estado=&apos;Aprobado&apos;
        ///and a.negociacion=&apos;Pendiente&apos;.
        /// </summary>
        internal static string NegocionsNoEnviadoNormal {
            get {
                return ResourceManager.GetString("NegocionsNoEnviadoNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///a.IdAdjudicacion,
        ///a.FechaContrato,
        ///a.Contrato,
        ///a.Trm,
        ///a.Valor,
        ///convert(ROUND((a.Valor*a.trm),2),decimal (18,2)) as ValorMonedaLocal,
        ///a.FinanciacionMfs,
        ///a.CuotaMfs,
        ///a.IdTercero1,
        ///t.nombrecompleto as Cliente
        ///from adjudicacion a 
        ///LEFT JOIN Contabilidad_alttum.terceros t on a.IdTercero1=t.IdTercero
        ///where a.tipooperacion=&apos;Monterey&apos;
        ///and a.negociacion=&apos;Pendiente&apos;.
        /// </summary>
        internal static string negociosnoenviadomonterey {
            get {
                return ResourceManager.GetString("negociosnoenviadomonterey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///a.IdAdjudicacion,
        ///a.FechaContrato,
        ///a.Contrato,
        ///a.Trm,
        ///a.Valor,
        ///convert(ROUND((a.Valor*a.trm),2),decimal (18,2)) as ValorMonedaLocal,
        ///a.FinanciacionMfs,
        ///a.CuotaMfs,
        ///a.IdTercero1,
        ///t.nombrecompleto as Cliente
        ///from adjudicacion a 
        ///LEFT JOIN Contabilidad_alttum.terceros t on a.IdTercero1=t.IdTercero
        ///where a.tipooperacion=&apos;Monterey&apos;
        ///and a.negociacion=&apos;Vacio&apos;.
        /// </summary>
        internal static string NegociosNoenviadovacio {
            get {
                return ResourceManager.GetString("NegociosNoenviadovacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///f.IdGestor,
        ///t.NombreCompleto,
        ///sum(f.Valor)ValorTotal 
        ///FROM fondosmonterrey f
        ///JOIN Contabilidad_alttum.terceros t
        ///ON f.IdGestor=t.IdTercero
        ///GROUP BY IdGestor .
        /// </summary>
        internal static string SaldoFondosMonterey {
            get {
                return ResourceManager.GetString("SaldoFondosMonterey", resourceCulture);
            }
        }
    }
}
