//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarteraGeneral {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RscAdjudicacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RscAdjudicacion() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarteraGeneral.RscAdjudicacion", typeof(RscAdjudicacion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        ///a.IdInmueble,
        ///a.Contrato,
        ///a.TipodeAdjudicacion as TipoSemana,
        ///a.Temporada,
        ///a.Grado,
        ///a.IdTercero1,
        ///a.IdTercero2,
        ///a.IdTercero3,
        ///a.Fecha as FechaElaboracion,
        ///a.FechaContrato,
        ///a.Trm,
        ///a.Valor as ValorContrato,
        ///a.GastosLegales,
        ///a.CuotaInicial,
        ///a.FinanciacionMfs,
        ///a.Financiacion,
        ///r.IdReserva,
        ///a.BaseComision
        ///from adjudicacion a
        ///join reservas r on a.idadjudicacion=r.idadjudicacion
        ///Where a.IdAdjudicacion=@Parametro1
        ///.
        /// </summary>
        internal static string CnsDatosAdjudicacionxAdj {
            get {
                return ResourceManager.GetString("CnsDatosAdjudicacionxAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select 
        ///f.Fecha,
        ///f.Capital Valor
        ///FROM 
        ///financiacion f
        ///Where concepto=&apos;CI&apos; AND IdAdjudicacion=@Parametro1.
        /// </summary>
        internal static string CnsDatosCuotaInicialxAdj {
            get {
                return ResourceManager.GetString("CnsDatosCuotaInicialxAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///Fecha,
        ///Concepto,
        ///NumCuota,
        ///Capital,
        ///Interes as InteresCte,
        ///Cuota
        ///from financiacion
        ///where IdAdjudicacion=@Parametro1
        ///AND Concepto !=&apos;GA&apos;
        ///ORDER BY Fecha.
        /// </summary>
        internal static string CnsDatosFinanciacionxAdj {
            get {
                return ResourceManager.GetString("CnsDatosFinanciacionxAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        ///Sum(Capital)ValorFncMfs,
        ///Count(Capital)PlazoFncMfs, 
        ///0 TasaFncMfs,
        ///30 PeriodoFncMfs,
        ///cuota CuotaFncMfs,
        ///min(fecha)
        ///FechaFncMfs
        ///FROM financiacion WHERE Concepto=&apos;CM&apos;
        ///AND idadjudicacion=@Parametro1
        ///.
        /// </summary>
        internal static string CnsDatosFncMontereyxAdj {
            get {
                return ResourceManager.GetString("CnsDatosFncMontereyxAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        ///Sum(Capital)ValorFncPh,
        ///Count(Capital)PlazoFncPh, 
        ///0 TasaFncPh,
        ///30 PeriodoFncPh,
        ///cuota CuotaFncPh,
        ///min(fecha)FechaFncPh
        ///FROM financiacion WHERE Concepto=&apos;FN&apos;
        ///AND idadjudicacion=@Parametro1.
        /// </summary>
        internal static string CnsDatosFncPobladoxAdj {
            get {
                return ResourceManager.GetString("CnsDatosFncPobladoxAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Select 
        /// i.IdInmueble,
        /// i.TipodeSemana,
        /// i.Villa,
        /// i.Unidad,
        /// i.Semana,
        /// i.Temporada, 
        ///if(a.Cliente is null,&apos;SIN ADJUDICAR&apos;,a.Cliente)Cliente,
        ///if(a.FechaContrato is null,curdate(),a.FechaContrato)FechaContrato,
        /// upper(i.Estado)Estado 
        /// From Inmuebles  i
        ///left join   
        ///
        ///(
        ///select a.IdAdjudicacion  ,a.IdInmueble,a.FechaContrato,c.NombreCompleto AS Cliente
        ///from adjudicacion a join Contabilidad_alttum.terceros c on c.IdTercero = a.IdTercero1
        ///where a.Estado != &apos;Desistido&apos; and a.Estado != &apos;DesistidoJuridic [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string CnsInmuebles {
            get {
                return ResourceManager.GetString("CnsInmuebles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select  a.IdAdjudicacion,a.IdTercero1,t.NombreCompleto Cliente,a.Fecha,a.Contrato,a.IdInmueble,a.TipodeAdjudicacion,a.Temporada,
        ///upper(a.Grado)Grado,a.TipoOperacion,
        ///a.Valor,Upper(a.Estado)Estado From adjudicacion a 
        ///join Contabilidad_alttum.terceros t
        ///on t.idtercero=a.idtercero1
        ///Where (Estado=&apos;Pendiente&apos; or Estado=&apos;Aprobado&apos;) 
        ///and Radicacion=&apos;Pendiente&apos;.
        /// </summary>
        internal static string CnsRadicaciones {
            get {
                return ResourceManager.GetString("CnsRadicaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        ///a.IdReserva,
        ///UPPER(a.TipoReserva) AS TipoSemana,
        ///a.IdInmueble,
        ///a.Fecha,
        ///a.ValorContrato,
        ///a.FechaInicio AS FchRadica,
        ///a.ValorPago1 AS VrRadica,
        ///a.Estado,
        ///a.IdTercero1,
        ///003cnsadjudica.Titular1,
        ///a.IdGestor,
        ///001cnsgestor.Nombres
        ///FROM
        ///reservas AS a
        ///LEFT JOIN  001cnsgestor ON a.IdGestor = 001cnsgestor.IdTercero
        ///LEFT JOIN 003cnsadjudica ON a.IdTercero1 = 003cnsadjudica.idTercero1
        ///WHERE
        ///a.Estado = &apos;Pendiente&apos;.
        /// </summary>
        internal static string CnsReservas {
            get {
                return ResourceManager.GetString("CnsReservas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select  o.IdAdjudicacion,o.IdOtrosi, a.IdTercero1,t.NombreCompleto Cliente,o.Fecha,a.Contrato,a.IdInmueble,a.TipodeAdjudicacion,a.Temporada,
        ///upper(a.Grado)Grado,a.TipoOperacion,
        ///a.Valor,Upper(a.Estado)Estado 
        ///From Otrosi o
        ///join adjudicacion a 
        ///on o.idadjudicacion=a.idadjudicacion
        ///join Contabilidad_alttum.terceros t
        ///on t.idtercero=a.idtercero1
        ///Where o.Estado=&apos;Pendiente&apos; .
        /// </summary>
        internal static string OtrsisPendientes {
            get {
                return ResourceManager.GetString("OtrsisPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT a.IdReserva, UPPER(a.TipoReserva) AS TipoSemana, a.IdInmueble, a.Fecha,a.ValorContrato, t.NombreCompleto AS Cliente, 
        ///g.NombreCompleto AS Asesor, a.FechaInicio AS FchRadica, a.ValorPago1 AS VrRadica, a.Estado
        ///FROM Reservas a
        ///LEFT JOIN Contabilidad_alttum.terceros t ON t.IdTercero = a.IdTercero1
        ///LEFT JOIN Contabilidad_alttum.Terceros g ON g.IdTercero=a.idgestor
        ///WHERE a.Estado=&apos;Pendiente&apos;.
        /// </summary>
        internal static string ReservasPendientes {
            get {
                return ResourceManager.GetString("ReservasPendientes", resourceCulture);
            }
        }
    }
}
