//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarteraGeneral {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RscPresupuesto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RscPresupuesto() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarteraGeneral.RscPresupuesto", typeof(RscPresupuesto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT p2.*,
        ///p2.RecaudoGestionado/Presupuesto Cumpl,
        ///0 Rango
        ///FROM
        ///(
        ///SELECT
        ///p.IdAdjudicacion,
        ///p.Cliente,
        ///p.Presupuesto,
        ///p.DiasCpt,
        ///if(p.Recaudo &gt; p.Presupuesto,p.Presupuesto,p.Recaudo)RecaudoGestionado,
        ///if(p.Recaudo &gt; p.Presupuesto,p.Recaudo-p.Presupuesto,0)RecaudoNoEsperado,
        ///p.Recaudo TotalRecaudo,
        ///p.Asesor
        ///From
        ///(
        ///Select p.*,
        ///if(r.Recaudo is null,0,r.recaudo)Recaudo
        ///From 
        ///(
        ///SELECT
        ///p.IdAdjudicacion,
        ///sum(p.Cuota) Presupuesto,
        ///max(p.DiasCpt)DiasCpt,
        ///Cliente,
        ///p.Asesor
        ///from   cartera_co [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string CumplimientoPresupuesto {
            get {
                return ResourceManager.GetString("CumplimientoPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT p2.*,
        ///p2.RecaudoGestionado/Presupuesto Cumpl,
        ///0 Rango
        ///FROM
        ///(
        ///SELECT
        ///p.IdAdjudicacion,
        ///p.Cliente,
        ///p.Presupuesto,
        ///p.DiasCpt,
        ///if(p.Recaudo &gt; p.Presupuesto,p.Presupuesto,p.Recaudo)RecaudoGestionado,
        ///if(p.Recaudo &gt; p.Presupuesto,p.Recaudo-p.Presupuesto,0)RecaudoNoEsperado,
        ///p.Recaudo TotalRecaudo,
        ///p.Asesor
        ///From
        ///(
        ///Select p.*,
        ///if(r.Recaudo is null,0,r.recaudo)Recaudo
        ///From 
        ///(
        ///SELECT
        ///p.IdAdjudicacion,
        ///sum(p.Cuota) Presupuesto,
        ///max(p.DiasCpt)DiasCpt,
        ///Cliente,
        ///p.Asesor
        ///from   cartera_co [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string CumplimientoPresupustoMetas {
            get {
                return ResourceManager.GetString("CumplimientoPresupustoMetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 
        ///Select p.*,c.Asesor
        ///From
        ///(
        ///SELECT
        ///convert((Car.Id),char)Id,
        ///convert((Car.IdAdjudicacion),char)IdAdjudicacion,
        ///tipo.Cliente AS Cliente,
        ///Car.Concepto Cto,
        ///Car.CuotaNum NCta,
        ///Car.Fecha,
        ///Car.FechaRec AS UltPago,
        ///Car.Capital,
        ///Car.Interes,
        ///Car.Cuota,
        ///Car.DiasCpt,
        ///Car.Diaslqd,
        ///Car.Mora,
        ///Tipo.TipoCartera,
        ///Tipo.Estado
        ///FROM
        ///	(
        ///SELECT
        ///rr.Id,
        ///rr.Idadjudicacion,
        ///rr.Concepto,
        ///rr.CuotaNum,
        ///Max(rr.Fecha) Fecha,
        ///IF (Max(rr.FechaRec) IS NULL,	rr.Fecha,		Max(rr.FechaRec)	) FechaRec,		sum(rr.Capita [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string PresupuestoGral {
            get {
                return ResourceManager.GetString("PresupuestoGral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select p.IdAdjudicacion,p.Cliente,max(p.DiasMoraInt)DiasMoraInt ,sum(p.Cuota)Cuota, sum(p.SdoCuota)SdoCuota,max(diasCpt)diasCpt,
        ///if(((p.DiasMoraInt &gt;= -(2)) and (p.DiasMoraInt &lt;= 0)),&apos;L1&apos;,if(((p.DiasMoraInt &gt;= 1) and (p.DiasMoraInt &lt; 10)),&apos;L2&apos;,if(((p.DiasMoraInt &gt;= 10) and (p.DiasMoraInt &lt;= 15)),&apos;L3&apos;,if(((p.DiasMoraInt &gt;= 16) and (p.DiasMoraInt &lt;= 30)),&apos;C1&apos;,if(((p.DiasMoraInt &gt;= 31) and (p.DiasMoraInt &lt;= 60)),&apos;C2&apos;,if(((p.DiasMoraInt &gt;= 61) and (p.DiasMoraInt &lt;= 90)),&apos;C3&apos;,if(((p.DiasMoraInt &gt;= 91) and (p.Di [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SegPresupuesto {
            get {
                return ResourceManager.GetString("SegPresupuesto", resourceCulture);
            }
        }
    }
}
